name: Android CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Build
      run: ./gradlew clean build

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Harmonika.apk
        path: app/build/outputs/apk/debug/app-debug.apk
